### ISSUE TITLE
The only thing that appears is the main window and the context menu

### ISSUE THREAD

**Issue by Futhark1988** [KurtisLiggett/GuiBuilderPlus#5]
It doesn't matter whether I start the .exe-file or the .au3-script I always get the same empty window.
Version: Win10 Home 21H1
Autoit: v3.3.14.5

![image](https://user-images.githubusercontent.com/12551657/172029886-33dcbcda-a779-40a5-b9d2-5be44c44f846.png)

**Comment by KurtisLiggett** [comment]
Was it working previously and just started this behavior?
I suspect it is trying to open the other windows off your screen. Try deleting the ini file in the storage folder then opening the program again.

I will work on a solution to check the screen resolution when opening the app to prevent it from showing off screen.

**Comment by Futhark1988** [comment]
It didn't work at all as I have just downloaded it andwanted to give it a try.
I deleted the ini-file but it didn't help one bit.

But I noticed something else. If you change  the windows size from 400x350 to anything bigger then the context menu (which only contains Paste on the screenshot) will only appear in the default 400x350 area.

**Comment by KurtisLiggett** [comment]
OK, I tried deleting my INI file and now I get the same behavior you are seeing. It is a bug with the window position.
Try editing your INI file like this:
```
[Settings]
posMain=760,365
posToolbar=543,365
```

**Comment by Futhark1988** [comment]
Brilliant!
That seems to havesolved the problem.
At first start-up and after the deletion of the INI-file it writes a negative value to the toolbar position.

[Settings]
posMain=483,209
posToolbar=-221,111

**Comment by KurtisLiggett** [comment]
Try the new version v0.26.
This was a separate issue but both issues should be fixed in this version. You can just post here if the new one works ok for you.

**Comment by Futhark1988** [comment]
Hi!

The context menu appears now even in bigger windows.
The standalone .exe-file starts but the buttons don't have any icons in
v0.26.
I think you can close this issue and I'll open a new one for this.

[image: image.png]

Kurtis Liggett ***@***.***> ezt írta (időpont: 2022. jún. 5.,
V, 16:23):
