### ISSUE TITLE
Icons missing in the standalone (exe) GuiBuilderPlus

### ISSUE THREAD

**Issue by Futhark1988** [KurtisLiggett/GuiBuilderPlus#6]
The icons of the buttons in the standalone GuiBuilderPlus are missing.
The exe doesn't come with the bundled resources folder.

Version: Win10 Home 21H1
Autoit: v3.3.14.5
GuiBuilderPlus: v0.26

![image](https://user-images.githubusercontent.com/12551657/172056217-5c6b3b35-dad3-42d8-a0da-56930c1e5003.png)

**Comment by KurtisLiggett** [comment]
You are correct, thanks for pointing that out. I can see how it was misleading to just stick the exe out there as a download.
In the future I will pack it all into the exe, or just provide a zip with the exe and required resource files.

**Comment by KurtisLiggett** [comment]
@Futhark1988  please check [v0.27](https://github.com/KurtisLiggett/GuiBuilderPlus/releases/tag/0.27) for an updated version with the program icons built in.

**Comment by Futhark1988** [comment]
The ListView still doesn't have an icon.

![image](https://user-images.githubusercontent.com/12551657/173193116-318dbe24-5a77-48da-b34d-b241888a1a77.png)

**Comment by KurtisLiggett** [comment]
Right again... guess I can't count.
