### ISSUE TITLE
UpDown control - Field disappears after moving it

### ISSUE THREAD

**Issue by Futhark1988** [KurtisLiggett/GuiBuilderPlus#8]
The filed of the UpDown control disappears after moving it (in any direction). 
It is pissible to make it visible again by resizing it.

Version: Win10 Home 21H1
Autoit: v3.3.14.5
GuiBuilderPlus: v0.27

![image](https://user-images.githubusercontent.com/12551657/173193478-765c33f4-8801-444f-9df3-6bc84d0c0474.png)

**Comment by KurtisLiggett** [comment]
Thanks for catching that! Looks like it broke in v0.25. It will be fixed in the next release.
