### ISSUE TITLE
Tabbed view - Added controls are shown on all tabs

### ISSUE THREAD

**Issue by Futhark1988** [KurtisLiggett/GuiBuilderPlus#9]
**Summary:**
When adding a UI element to a tabbed view it should only be visible on the tab to which it was added but not on the other tabs.

**Steps to reproduce:**
1.  Add tab to window
2.  Add another tab
3.  Add a button (or any other control)
4.  Test GUI

**Current result:**
The added control is shown on all tabs and not just on the one to which it was added.

**Expected result:**
The added control should only be visible n the tab to which it was added.

Version: Win10 Home 21H1
Autoit: v3.3.14.5
GuiBuilderPlus: v0.27

**Comment by KurtisLiggett** [comment]
Adding controls to tabs is still on the roadmap. Same with Group controls

**Comment by KurtisLiggett** [comment]
closing as this is not an issue since this feature is still in development and does not yet exist.
